sudo: required
dist: trusty
before_install:
- "./scripts/setup.sh"
script:
- "./scripts/build.sh"
deploy:
  provider: releases
  api_key:
    secure: T3PU0DwECdrkq8kYz6h22TiPyEc8BMkb6phmj53xU4KYOYbWCaeHgbyz6lyK5Dj/B1DBAz+mp5kE/+RZk3FUol608U41RyhJ/Rcg2S83gEE1jCZAjVHNIJxfYMZ3HjELRhtVmrEAdyrWsL6oQ7jkYgdY6Yiv7efGPd1BvWwA8zo8C3Jly55G5w7DLE19w3Ks97dNWCxOVWCOuZQq+hflGReJdgsPAWGmbeYJX9wRhAKxZRqjss4ZWsBdpkSEc27mUSUiT0puQMnjVr+mk12pHftizQpNNQ4B6H2axMAgbtI9w/cb1s5kC20yS8hNAY+RnpixNaZforTA8zZcQGXljiGVZe0nZpntgAzeHCSzfFJzZr4JpAsptJ4ELAGUkbamZbjppIxnV7tstKCvICgmCJ99LsktBWtVA5R7jmnoTn4ZiHdWOQcSSr8Rte0rxJ1mXqITITQSltY8R5iC8tMtjr7tJWJiwFcj9PMhH+BJDnIWgFbMqZ4654NSZzeZ5NeYI3DwmpDsRA7syqyBG0aFN9C4MnfrqST73E8AxG6/WMYMdFErZT/BYjUgOLXWbLtB/CfgvdeILY4bi6dkjepb0FxTqPLQlmO3nyh/srPBxRi+4xI5kUxu4WdRKiULlZNB0TKwz+UYaTBfy5ZvIt9W29IvTf03FFZJRMebPky9Dp4=
  file: "*/*pdf"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
